### ISSUE TITLE
Why do you mask the feat here?

### ISSUE THREAD

**Issue by Chinartist** [GANWANSHUI/SimpleOccupancy#12]
mask_mems = (torch.abs(feat_mems) > 0).float()
feat_mem = basic.reduce_masked_mean(feat_mems, mask_mems, dim=1)  # B, C, Z, Y, X
feat_mem = feat_mem.permute(0, 1, 4, 3, 2) # [0, ...].unsqueeze(0) # ZYX -> XYZ

**Comment by GANWANSHUI** [comment]
This function is from [simple-bev](https://github.com/aharley/simple_bev), the main purpose is to provide the number of the projected camera of each 3d points (voxel), which is for the [mean operation](https://github.com/GANWANSHUI/SimpleOccupancy/blob/7d3232e67e51b769191787c7866c90395285a53b/utils/basic.py#L49) .

**Comment by Chinartist** [comment]
Tks!
