### ISSUE TITLE
Release of source code and pretrained weights

### ISSUE THREAD

**Issue by aselimc** [GANWANSHUI/SimpleOccupancy#3]
Hello,

I have read your paper. I was wondering if you are going to publish model that is trained on nuScenes data? Furthermore, if possible, do you have any time schedule to finalize and publish the source code that you can share publicly?

Thanks in advance.

**Comment by GANWANSHUI** [comment]
Hi, considering this work is still under peer review and also still under construction, the final code and pre-trained model may not be that fast to release (maybe within a month), but open to answering the questions you are interested in.

**Comment by aselimc** [comment]
Thanks for the update

**Comment by YIQIHYM** [comment]
Thanks!

**Comment by GANWANSHUI** [comment]
The primary code has been released. Thanks!
