### ISSUE TITLE
Is it convenient to provide more details and parameters of volume rendering?

### ISSUE THREAD

**Issue by chenzyhust** [GANWANSHUI/SimpleOccupancy#4]
Such as near, far, n_samples, etc.

**Comment by GANWANSHUI** [comment]
Hi, we did not define the near and far like the bounded scene in NeRF, but we define the real size of the voxel. Here, we calculate the sampled point within the X ∈ (−52m, 52m), Z ∈ (0m, 6m), and Y ∈ (−52m, 52m). 

self.Z =  16
self.Y =  256
self.X = 256
self.stepsize =0.5

 N_samples = int(np.linalg.norm(np.array([self.Z // 2, self.Y // 2, self.X // 2]) + 1) / self.stepsize) + 1

The density of the sampled point out of the voxel would be set as 0, and the last sampled point is explicitly set as 1.

**Comment by chenzyhust** [comment]
Isn't voxel predicted in the lidar coordinate system? Why is the real size range of Z not [-5, 3] but [0, 6]

> Hi, we did not define the near and far like the bounded scene in NeRF, but we define the real size of the voxel. Here, we calculate the sampled point within the X ∈ (−52m, 52m), Z ∈ (0m, 6m), and Y ∈ (−52m, 52m).
> 
> self.Z = 16 self.Y = 256 self.X = 256 self.stepsize =0.5
> 
> N_samples = int(np.linalg.norm(np.array([self.Z // 2, self.Y // 2, self.X // 2]) + 1) / self.stepsize) + 1
> 
> The density of the sampled point out of the voxel would be set as 0, and the last sampled point is explicitly set as 1.

Isn't voxel predicted in the lidar coordinate system? Why is the real size range of Z not [-5, 3] but [0, 6]

**Comment by GANWANSHUI** [comment]
In our experiment, we define the Z above the ego coordinate. You may also set the range in [-5, 3]. The voxel is defined in the ego coordinate, not the lidar coordinate.

**Comment by chenzyhust** [comment]
One more question，Is the rendering 95ms in the paper run on the existing cuda acceleration implementation or torch?

**Comment by GANWANSHUI** [comment]
just with the torch implementation
