### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by lvchuandong** [GANWANSHUI/SimpleOccupancy#6]
Could you provide requirements.txt? Thank you very much.

**Comment by GANWANSHUI** [comment]
Please refer to the requirement in https://github.com/weiyithu/SurroundDepth, and the additional library is open3d

**Comment by lvchuandong** [comment]
> Please refer to the requirement in https://github.com/weiyithu/SurroundDepth, and the additional library is open3d

Thank you very much.
