### ISSUE TITLE
Poind Cloud Processing for nuScenes?

### ISSUE THREAD

**Issue by sithu31296** [GANWANSHUI/SimpleOccupancy#7]
I see the point cloud processing file for nuscenes in tools but it is incomplete.
Could you upload the complete file and the label path in [L41](https://github.com/GANWANSHUI/SimpleOccupancy/blob/a128c8e3eac4211b89c7e7f63b270d814f36ab1b/datasets/nusc_dataset.py#L41)?

**Comment by GANWANSHUI** [comment]
You can refer to this [function](https://github.com/GANWANSHUI/SimpleOccupancy/blob/a128c8e3eac4211b89c7e7f63b270d814f36ab1b/datasets/mono_dataset.py#L304C3-L304C3) to generate the test label, focusing on the discrete depth metric is OK, but we also provide the code classification metric. Note that the generate the test label for discrete depth metric is relatively large, around 160 GB.

**Comment by sithu31296** [comment]
Thank you.
